version: '3.9'
services:
  web:
    build: .
    command:  python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db
      
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      MYSQL_HOST: localhost 
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - "33066:3306"
