# Generated by Django 3.1.7 on 2021-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_client', models.CharField(max_length=100)),
                ('order', models.ManyToManyField(to='BenutzerSicht.Order')),
            ],
        ),
    ]
