# Generated by Django 3.1.7 on 2021-03-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunde',
            name='geheimeFA',
        ),
        migrations.DeleteModel(
            name='GeheimeFA',
        ),
    ]
