# Generated by Django 3.1.7 on 2021-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0002_auto_20210330_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['headline']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='order_client',
            new_name='headline',
        ),
    ]
