# Generated by Django 3.1.7 on 2021-03-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0002_auto_20210325_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('message_title', models.CharField(max_length=70)),
                ('message', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Kunde',
        ),
    ]
