# Generated by Django 3.1.7 on 2021-03-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0003_auto_20210327_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
