# Generated by Django 3.1.7 on 2021-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0003_auto_20210330_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('progress', 'In Progress'), ('fineshed', 'Fineshed'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='created', max_length=20),
        ),
    ]
