# Generated by Django 3.1.7 on 2021-03-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0004_auto_20210327_0935'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catagory',
            table=None,
        ),
    ]
