# Generated by Django 3.1.7 on 2021-03-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0005_auto_20210327_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagory',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
