# Generated by Django 3.1.7 on 2021-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenutzerSicht', '0005_auto_20210330_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('checked', 'Checked')], default='sent', max_length=20),
        ),
    ]
