# Generated by Django 3.1.7 on 2021-03-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadt', models.CharField(max_length=200)),
                ('pstl_zahl', models.PositiveIntegerField()),
                ('strasse', models.CharField(max_length=300)),
                ('haus_nr', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bestellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellung_nummer', models.PositiveIntegerField()),
                ('bestellung_name', models.CharField(max_length=200)),
                ('bestellung_anzahl', models.PositiveIntegerField()),
                ('bestellung_zeit', models.DateField()),
                ('extra_wuensche', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeheimeFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geheime_frage', models.TextField()),
                ('geheime_antwort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('address', models.TextField()),
                ('position', models.TextField(default='This is not cool')),
            ],
        ),
        migrations.CreateModel(
            name='Rohe_Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('produkt_art', models.CharField(max_length=200)),
                ('anzahl', models.PositiveIntegerField()),
                ('beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('benutzer_name', models.CharField(max_length=200)),
                ('email_add', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=300)),
                ('geheimeFA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kundenInfo', to='zweiteSicht.geheimefa')),
            ],
        ),
    ]
