# Generated by Django 3.1.7 on 2021-03-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zweiteSicht', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='position',
            field=models.TextField(default='This is not cool'),
        ),
    ]
