# Generated by Django 3.1.7 on 2021-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zweiteSicht', '0003_rohe_produkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadt', models.CharField(max_length=200)),
                ('pstl_zahl', models.PositiveIntegerField()),
                ('strasse', models.CharField(max_length=300)),
                ('haus_nr', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bestellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellung_nummer', models.PositiveIntegerField()),
                ('bestellung_name', models.CharField(max_length=200)),
                ('bestellung_anzahl', models.PositiveIntegerField()),
                ('bestellung_zeit', models.DateField()),
                ('extra_wuensche', models.TextField()),
            ],
        ),
    ]
