# Generated by Django 3.1.7 on 2021-03-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zweiteSicht', '0004_addresse_bestellungen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('benutzer_name', models.CharField(max_length=200)),
                ('email_add', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=300)),
            ],
        ),
    ]
