# Generated by Django 3.1.7 on 2021-03-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeheimeFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geheime_frage', models.TextField()),
                ('geheime_antwort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=200)),
                ('nachname', models.CharField(max_length=200)),
                ('benutzer_name', models.CharField(max_length=200)),
                ('email_add', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=300)),
                ('geheimeFA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kundenInfo', to='BenutzerSicht.geheimefa')),
            ],
        ),
    ]
